fix precommit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,8 +3,8 @@
 
 echo 'Will proceed to check code format and lint! 😁'
 
-npm run check || (
-    echo 'Issues with code formatting! Please use Prettier and refer to above errors! Run `npm run format` to format code. 🚫'
+npm run format || (
+    echo 'Issues with code formatting! Please use Prettier and refer to above errors! 🚫'
     false;
 )
 
